// Copyright 2023 kushima8 (@kushima8)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#ifdef RGBLIGHT_ENABLE
#    undef RGBLIGHT_EFFECT_BREATHING
#    undef RGBLIGHT_EFFECT_RAINBOW_MOOD
#    undef RGBLIGHT_EFFECT_RAINBOW_SWIRL
#    undef RGBLIGHT_MODE_SNAKE
#    undef RGBLIGHT_MODE_KNIGHT
#    undef RGBLIGHT_MODE_CHRISTMAS
#    undef RGBLIGHT_MODE_STATIC_GRADIENT
#    undef RGBLIGHT_EFFECT_RGB_TEST
#    undef RGBLIGHT_MODE_ALTERNATING
#    undef RGBLIGHT_MODE_TWINKLE
#endif

//#define REEX_PMW3360_UPLOAD_SROM_ID 0x04
#define REEX_PMW3360_UPLOAD_SROM_ID 0x81

#define NO_ACTION_ONESHOT

#define NO_ACTION_TAPPING

